### PR TITLE
Extract documentation even if a symbol has multiple definitions in the same file (#186)

### PR DESCRIPTION
**Pull request by cxw42**
The root cause of #186 was that find-file-doc-comments.pl was not properly checking symbols defined as a macro on one line of a file and as a function earlier in that file.  This PR:

- Adds tests of that situation, both for undocumented symbols (the failure mode in #186) and for documented symbols (for completeness)
- Modifies find-file-doc-comments.pl to always index by line, never by name, so it won't matter if a name is defined multiple times in one file 
- Cleans up verbose output in find-file-doc-comments.pl (but no substantive changes to that output)
- Fixes a typo

Thanks for considering this PR!

### CODE REVIEW

**Comment by michaelopdenacker** [comment]
Accepted, many thanks!
